### ISSUE TITLE
deploy.sh does not handle spaces in model filenames

### ISSUE THREAD

**Issue by osrf-migration** [osrf/gzweb#160]
**Original report ([archived issue](https://osrf-migration.github.io/gzweb-gh-pages/#!/osrf/gzweb/issues/160)) by Will Baker (Bitbucket: [William Baker](https://bitbucket.org/%7B29059f61-e8ef-4122-a6c9-ebf4207e716a%7D/)).**

----------------------------------------
```
#!bash

['sed', '-i', '-e', 's/\\(\\.tga\\|\\.tiff\\|\\.tif\\|\\.jpg\\|\\.jpeg\\|\\.gif\\)/\\.png/g', 'Male.dae']
sed: can't read Male.dae: No such file or directory
error Command '['sed', '-i', '-e', 's/\\(\\.tga\\|\\.tiff\\|\\.tif\\|\\.jpg\\|\\.jpeg\\|\\.gif\\)/\\.png/g', 'Male.dae']' returned non-zero exit status 2
Traceback (most recent call last):
  File "./webify_models_v2.py", line 67, in <module>
    subprocess.check_call(sed_cmd)
  File "/usr/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['sed', '-i', '-e', 's/\\(\\.tga\\|\\.tiff\\|\\.tif\\|\\.jpg\\|\\.jpeg\\|\\.gif\\)/\\.png/g', 'Male.dae']' returned non-zero exit status 2

```

Added a model that is named `Large Male`

```
#!bash
'Large Male'
├── materials
│   └── textures
│       └── Large Male.png
├── meshes
│   └── Large Male.dae
├── model.config
└── model.sdf
```

gazebo 9.4.1
Gzweb on branch insert_sdf
using docker file from issue #158
and [pull request #173](https://osrf-migration.github.io/gzweb-gh-pages/#!/osrf/gzweb/pull-requests/173)
https://osrf-migration.github.io/gzweb-gh-pages/#!/osrf/gzweb/pull-requests/173

**Comment by chapulina** [comment]
Here's the diff from @willcbaker's PR on BitBucket:

https://github.com/osrf/gzweb/compare/willcbaker/split-files-in-webify_models_v2py-by-new-1542660156446

That fixes serving all the files, but I'm needing more fixes for the files to actually load on the browser. I'm working on this branch:

https://github.com/osrf/gzweb/compare/gzweb_1.4...chapulina/spaces

I have meshes and textures with spaces being properly fetched by the browser, but for some reason the texture is not showing yet. It could be an issue unrelated to the spaces, I'll keep debugging.

I'm using this PR on Gazebo's side: https://github.com/osrf/gazebo/pull/2877
