### ISSUE TITLE
building gzweb 1.4.0 against node 12 (Gazebo11/ROS2)

### ISSUE THREAD

**Issue by newcanopies** [osrf/gzweb#204]
Can gzweb be deployed against node 12? 
rclnodejs (of ros2-web-bridge) module implementation requires Node 12.

Ubuntu Focal 20.04
ROS2 Foxy, Gazebo 11

STEPS: 
git checkout gzweb_1.4.0 (as per install instructions)
source   /usr/share/gazebo/setup.sh
[APPLIED Binding gyp & deploy.sh PATCHES](https://github.com/eurogroep/gzweb/commit/696148dc49b8a0ebd54d749c2e1a0d28189de120)
enable write permissions for deploy script
`sudo chmod +x ./scripts/deploy.sh`

npm run deploy --- -m local
```

> gzweb@1.3.0 deploy /home/user/gzweb
> ./deploy.sh "-m" "local"

Build a local model database.
Only local models.
npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN gzweb@1.3.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 769 packages in 5.439s

10 packages are looking for funding
  run `npm fund` for details

found 54 vulnerabilities (23 low, 11 moderate, 20 high)
  run `npm audit fix` to fix them, or `npm audit` for details
Running "concat:build_src" (concat) task

Running "concat:build_gz3d" (concat) task

Running "concat:build_gui" (concat) task

Running "jshint:files" (jshint) task
>> 2 files lint free.

Running "uglify:build_src" (uglify) task
>> 1 file created 1.48 MB → 693.93 kB

Running "uglify:build_gz3d" (uglify) task
>> 1 file created 1.48 MB → 693.93 kB

Running "uglify:build_gui" (uglify) task
>> 1 file created 2.13 MB → 1.14 MB

Done, without errors.
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- gzweb version 2.0.0
CMake Warning (dev) at CMakeLists.txt:23 (set):
  Policy CMP0053 is not set: Simplify variable reference and escape sequence
  evaluation.  Run "cmake --help-policy CMP0053" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  For input:

    '@PROJECT_NAME@-@GZWEB_VERSION_FULL@'

  the old evaluation rules produce:

    'gzweb-2.0.0'

  but the new evaluation rules produce:

    '@PROJECT_NAME@-@GZWEB_VERSION_FULL@'

  Using the old result for compatibility since the policy is not set.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Build type not selected: Release selected by default
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
CMake Error at CMakeLists.txt:38 (find_package):
  By not providing "Findgazebo.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "gazebo", but
  CMake did not find one.

  Could not find a package configuration file provided by "gazebo" with any
  of the following names:

    gazeboConfig.cmake
    gazebo-config.cmake

  Add the installation prefix of "gazebo" to CMAKE_PREFIX_PATH or set
  "gazebo_DIR" to a directory containing one of the above files.  If "gazebo"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "/home/user/gzweb/build/CMakeFiles/CMakeOutput.log".
There are cmake errors, exiting.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gzweb@1.3.0 deploy: `./deploy.sh "-m" "local"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gzweb@1.3.0 deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2021-01-22T13_44_42_730Z-debug.log

```

$ npm start

```
> gzweb@1.3.0 start /home/user/gzweb
> if [ $npm_config_port ]; then port=$npm_config_port; fi; cd gzbridge && ./server.js $port

internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module './build/Debug/gzbridge'
Require stack:
- /home/user/gzweb/gzbridge/server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/user/gzweb/gzbridge/server.js:9:18)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/home/user/gzweb/gzbridge/server.js' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gzweb@1.3.0 start: `if [ $npm_config_port ]; then port=$npm_config_port; fi; cd gzbridge && ./server.js $port`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gzweb@1.3.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2021-01-22T13_44_57_940Z-debug.log
```

**Comment by newcanopies** [comment]
Thanks for all your work in https://github.com/osrf/gzweb/pull/205#issuecomment-770409026 on gzweb Node12 support @FelipeGdM 

Using the updated [gzweb_1.4 branch](https://github.com/osrf/gzweb/tree/gzweb_1.4) this is deploy error against Node12:

Steps:
git clone https://github.com/osrf/gzweb.git  
git checkout git checkout gzweb_1.4
source /usr/share/gazebo/setup.sh  
npm run deploy  


```
gzweb$ npm run deploy

> gzweb@1.4.0 deploy /home/gzweb
> ./deploy.sh

npm WARN ajv-keywords@2.1.1 requires a peer of ajv@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN gzweb@1.4.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

audited 756 packages in 3.068s

9 packages are looking for funding
  run `npm fund` for details

found 55 vulnerabilities (23 low, 12 moderate, 20 high)
  run `npm audit fix` to fix them, or `npm audit` for details
Running "concat:build_src" (concat) task

Running "concat:build_gz3d" (concat) task

Running "concat:build_gui" (concat) task

Running "jshint:files" (jshint) task
>> 2 files lint free.

Running "uglify:build_src" (uglify) task
>> 1 file created 1.48 MB → 693.93 kB

Running "uglify:build_gz3d" (uglify) task
>> 1 file created 1.48 MB → 693.93 kB

Running "uglify:build_gui" (uglify) task
>> 1 file created 2.13 MB → 1.14 MB

Done, without errors.
-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is GNU 9.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- gzweb version 2.0.0
CMake Warning (dev) at CMakeLists.txt:23 (set):
  Policy CMP0053 is not set: Simplify variable reference and escape sequence
  evaluation.  Run "cmake --help-policy CMP0053" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  For input:

    '@PROJECT_NAME@-@GZWEB_VERSION_FULL@'

  the old evaluation rules produce:

    'gzweb-2.0.0'

  but the new evaluation rules produce:

    '@PROJECT_NAME@-@GZWEB_VERSION_FULL@'

  Using the old result for compatibility since the policy is not set.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Build type not selected: Release selected by default
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
CMake Error at CMakeLists.txt:38 (find_package):
  By not providing "Findgazebo.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "gazebo", but
  CMake did not find one.

  Could not find a package configuration file provided by "gazebo" with any
  of the following names:

    gazeboConfig.cmake
    gazebo-config.cmake

  Add the installation prefix of "gazebo" to CMAKE_PREFIX_PATH or set
  "gazebo_DIR" to a directory containing one of the above files.  If "gazebo"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "/home/gzweb/build/CMakeFiles/CMakeOutput.log".
There are cmake errors, exiting.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! gzweb@1.4.0 deploy: `./deploy.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the gzweb@1.4.0 deploy script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/.npm/_logs/2021-03-31T12_25_48_089Z-debug.log
```

DEBUG LOG BELOW
<details>
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/home/.nvm/versions/node/v12.20.0/bin/node',
1 verbose cli   '/home/.nvm/versions/node/v12.20.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'deploy'
1 verbose cli ]
2 info using npm@6.14.8
3 info using node@v12.20.0
4 verbose run-script [ 'predeploy', 'deploy', 'postdeploy' ]
5 info lifecycle gzweb@1.4.0~predeploy: gzweb@1.4.0
6 info lifecycle gzweb@1.4.0~deploy: gzweb@1.4.0
7 verbose lifecycle gzweb@1.4.0~deploy: unsafe-perm in lifecycle true
8 verbose lifecycle gzweb@1.4.0~deploy: PATH: /home/.nvm/versions/node/v12.20.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/gzweb/node_modules/.bin:/opt/ros/foxy/bin:/home/esofi/.vscode-server/bin/ea3859d4ba2f3e577a159bc91e3074c5d85c0523/bin:/home/esofi/.local/bin:/home/esofi/.nvm/versions/node/v12.20.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Python27/:/mnt/c/Python27/Scripts:/mnt/c/Program Files/Microsoft HPC Pack 2008 R2/Bin/:/mnt/c/Program Files (x86)/Common Files/Intel/Shared Libraries/redist/intel64_win/compiler:/mnt/c/Program Files (x86)/Razer Chroma SDK/bin:/mnt/c/Program Files/Razer Chroma SDK/bin:/mnt/c/Program Files (x86)/Razer/ChromaBroadcast/bin:/mnt/c/Program Files/Razer/ChromaBroadcast/bin:/mnt/c/Windows/system32:/mnt/c/Windows:/mnt/c/Windows/System32/Wbem:/mnt/c/Windows/System32/WindowsPowerShell/v1.0/:/mnt/c/Windows/System32/OpenSSH/:/mnt/c/Program Files (x86)/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Program Files/Intel/Intel(R) Management Engine Components/DAL:/mnt/c/Users/Administrator/AppData/Local/Microsoft/WindowsApps:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/

9 verbose lifecycle gzweb@1.4.0~deploy: CWD: /home/gzweb
10 silly lifecycle gzweb@1.4.0~deploy: Args: [ '-c', './deploy.sh' ]
11 silly lifecycle gzweb@1.4.0~deploy: Returned: code: 1  signal: null
12 info lifecycle gzweb@1.4.0~deploy: Failed to exec deploy script
13 verbose stack Error: gzweb@1.4.0 deploy: `./deploy.sh`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/esofi/.nvm/versions/node/v12.20.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:314:20)
13 verbose stack     at ChildProcess.<anonymous> (/home/esofi/.nvm/versions/node/v12.20.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:314:20)
13 verbose stack     at maybeClose (internal/child_process.js:1022:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
14 verbose pkgid gzweb@1.4.0
15 verbose cwd /home/gzweb
16 verbose Linux 5.4.72-microsoft-standard-WSL2
17 verbose argv "/home/esofi/.nvm/versions/node/v12.20.0/bin/node" "/home/esofi/.nvm/versions/node/v12.20.0/bin/npm" "run" "deploy"
18 verbose node v12.20.0
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 1
22 error gzweb@1.4.0 deploy: `./deploy.sh`
22 error Exit status 1
23 error Failed at the gzweb@1.4.0 deploy script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
</details>
